import Link from "next/link";
import { ShareButton } from "@/components/share-button";
import { db } from "@/lib/db";
import { formatDate, formatNumber, requireSpeaker, statusLabels } from "@/lib/dashboard";

export default async function MyArticles({ searchParams }: { searchParams: Promise<{ created?: string; updated?: string }> }) {
  const user = await requireSpeaker(); const { created, updated } = await searchParams;
  const articles = await db.article.findMany({ where: { authorId: user.id, deletedAt: null }, include: { category: true }, orderBy: { updatedAt: "desc" } });
  return <><div className="dash-head"><div><span className="eyebrow">Mes publications</span><h1>Mes articles</h1></div><Link className="button violet" href="/dashboard/new-article">Nouvel article</Link></div>{created && <p className="form-success">Ton article a bien été enregistré.</p>}{updated && <p className="form-success">Ton article a bien été mis à jour.</p>}<div className="panel">{articles.length ? <table className="simple-table"><thead><tr><th>Titre</th><th>Catégorie</th><th>Statut</th><th>Dernière modification</th><th>Résultats</th><th>Actions</th></tr></thead><tbody>{articles.map((article) => <tr key={article.id}><td className="cell-title"><Link href={`/dashboard/articles/${article.id}`}><b>{article.title}</b></Link>{article.rejectionReason && <small className="rejection">Motif : {article.rejectionReason}</small>}</td><td data-label="Catégorie">{article.category.name}</td><td data-label="Statut"><span className={`status status-${article.status.toLowerCase()}`}>{statusLabels[article.status]}</span></td><td data-label="Modifié le">{formatDate(article.updatedAt)}</td><td data-label="Résultats">{formatNumber(article.views)} vues · {formatNumber(article.voteCount)} votes · {formatNumber(article.commentCount)} commentaire{article.commentCount !== 1 ? "s" : ""}</td><td className="cell-action article-row-actions">{article.status !== "ARCHIVED" && <Link className="button small outline" href={`/dashboard/articles/${article.id}/edit`}>{article.status === "DRAFT" ? "Continuer" : "Modifier"}</Link>}{article.status === "APPROVED" ? <ShareButton slug={article.slug} title={article.title} /> : article.status === "ARCHIVED" ? <small className="share-note">Article archivé</small> : null}</td></tr>)}</tbody></table> : <div className="empty-note">Aucun article pour le moment.<br /><br /><Link className="button small" href="/dashboard/new-article">Écrire mon premier article</Link></div>}</div></>;
}
